# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MÃºsica de Emmanuel Cabrera
email: emmanuelcabrer6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Biography, music and news for Emmanuel Cabrera, young composer and pianist from
  Queretaro, Mexico who specializes in Flamenco, Waltzes, Pasodoble and New Age.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://musicemmanuel.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"
